version: "3"

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: always
    volumes:
      - mariadb_volume:/var/lib/mysql
    networks:
    - inception
    env_file:
      - .env

  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    build: ./requirements/wordpress
    restart: always
    volumes:
      - wordpress_volume:/var/www/wordpress
    networks:
      - inception
    env_file:
      - .env

  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    build: ./requirements/nginx
    restart: always
    volumes:
      - wordpress_volume:/var/www/wordpress
    networks:
      - inception
    ports:
      - "443:443"
    env_file:
      - .env

volumes:
  mariadb_volume:
    name: mariadb_volume
    driver: local
    driver_opts:
      device: /home/mhaddi/data/mariadb
      o: bind
      type: volume

  wordpress_volume:
    name: wordpress_volume
    driver: local
    driver_opts:
      device: /home/mhaddi/data/wordpress
      o: bind
      type: volume

networks:
  inception:
