# set up a network of the following containers:
# - A Docker container that contains NGINX with TLSv1.2 or TLSv1.3 only.
# - A Docker container that contains WordPress + php-fpm (it must be installed and configured) only without nginx.
# - A Docker container that contains MariaDB only without nginx.
# - A volume that contains your WordPress database.
# - A second volume that contains your WordPress website files.

# add the line `network: bridge`, although bridge is the default network, the subject requires to add this line still.

# don't use `links` (not only because it's forbidden but because it's deprecated and useless).

# in your WordPress database there must be two users, one of them being the administrator. The admin’s username can’t contain admin/Admin... etc.

# volumes should be available in the /home/login/data folder of the host machine.

# To make things simpler, you have to configure your domain name so it points to your local IP address. This domain name must be login.42.fr. 

# The `latest` tag is prohibited.

# No password must be present in your Dockerfiles.

# It is mandatory to use environment variables.

# Also, it is strongly recommended to use a .env file to store environment variables. The .env file should be located at the root of srcs/.

# Your NGINX container must be the only entrypoint into your infrastructure via the port 443 only, using the TLSv1.2 or TLSv1.3 protocol.
# (So only NGINX will route host port to the container's. MariaDB and WordPress's ports will just be exposed)
