# To make things simpler, you have to configure your domain name so it points to your local IP address. This domain name must be login.42.fr. 
# No password must be present in your Dockerfiles. It is mandatory to use environment variables.
# If you use a .env file to store environment variables, it should be located at the root of srcs/.

version: "3"

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: always
    volumes:
      - /Users/haddi/data/mariadb:/var/lib/mysql
    networks:
    - inception

  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    build: ./requirements/wordpress
    restart: always
    volumes:
      - /Users/haddi/data/wordpress:/var/www/wordpress
    networks:
      - inception

  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    build: ./requirements/nginx
    restart: always
    volumes:
      - /Users/haddi/data/wordpress:/var/www/wordpress
    networks:
      - inception
    ports:
      - "443:443"

volumes:
  mariadb_volume:
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/Users/haddi/data/mariadb'

  wordpress_volume:
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/Users/haddi/data/wordpress'

networks:
  inception: