version: '3'

services:

  mariadb-srv:
    build: ./requirements/mariadb
    container_name: mariadb-cnt
    ports:
      - "3306:3306"
    volumes:
      - ./requirements/mariadb/db:/var/lib/mysql
    restart: always

  wordpress-srv:
    build: ./requirements/wordpress
    container_name: wordpress-cnt
    ports:
      - "9000:9000"
    volumes:
      - ./requirements/wordpress/site:/var/www/html
    restart: always
    depends_on:
      - mariadb

  nginx-srv: 
    build: ./requirements/nginx/
    container_name: nginx-cnt
    ports:
      - "80:80"
    volumes:
      - ./requirements/wordpress/site:/var/www/html
    restart: always
    depends_on:
      - wordpress
